### PR TITLE
adding william jasmine submission

### PR DESCRIPTION
**Pull request by williamzjasmine**
Pull request for my tidyverse CREATE submission.

### CODE REVIEW

**Comment by williamzjasmine** [comment]
My submission demonstrates how to enhance functional programming in R using the purr package (and specifically, its map function).

**Review by Anthogonyst — APPROVED** [review]
Looks good. May I have edit permissions so I may extend this?

**Comment by williamzjasmine** [comment]
Just added you as a collaborator on the repo, will that work?

**Comment by Anthogonyst** [comment]
Yeah, I think I can add a new commit now to the PR. Thanks.

**Comment by Anthogonyst** [comment]
Okay, my changes will be merged when you take the PR on your repo. Thanks again.

**Comment by williamzjasmine** [comment]
Glad it worked!

**Pull request merged**
